services:
  - type: web
    name: ivf-clinic-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build:backend
    startCommand: npm --prefix apps/backend run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://ivf_admin:IvfSecurePass2026!@200.234.42.142:5432/ivf_production?schema=public
      - key: APP_ACCESS_KEY_HASH
        value: ec189984c5b36432f04401eb55b916a4801153d10b627bc4cc590382e27d1aa8
      - key: JWT_ACCESS_SECRET
        value: dev_jwt_access_secret_super_secure_32_bytes_long_2026!
      - key: JWT_REFRESH_SECRET
        value: dev_jwt_refresh_secret_super_secure_32_bytes_long_2026!
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: srghivfcryo@gmail.com
      - key: SMTP_PASS
        value: vzba dnde aubt akas
      - key: SMTP_FROM
        value: '"SRGH IVF Cryo Bank" <srghivfcryo@gmail.com>'
